:icons: font
:last-update-label!:
:example-caption!:

= 翻译小测

从下面三个选段中 *选择一个*，将英文翻译成中文。 +
无标准答案，做到 *通顺易懂且符合语境* 即可。 +
限时 *30 分钟*，你可以参阅 *任何资料*。

NOTE: 该测试的文段全部基于游戏 *泰拉瑞亚* 及其 *模组*， +
词句的含义可能与日常生活中的有差别。

.选段 1：某物品的 wiki 页面
====
Stella Reaper is a craftable post-Moon Lord rogue boomerang. It rapidly throws high velocity scythes which can pierce through infinite enemies and pass through tiles. The scythe moves extremely quickly and ignores NPC immunity frames, allowing it to rack up enormous damage against large targets. When the scythes strike a target, it has 15% chance to summon a homing non-piercing astral star which deals 40% of the scythes damage and can create a small explosion on hit raining to a random enemy. The explosion deals 100 rouge damage and affected by damage bonuses. The scythes and the explosion will inflict God Slayer Inferno on any enemies hit.

Performing a stealth strike with the Stella Reaper causes 10 charged astral stars which deals 60% of the scythes damage raining towards the cursor's position. The charged astral stars cannot pierce but will create a big explosion when hitting any enemy or block. The big explosion will deal 200 rouge damage which is affected by damage bonuses and inflict God Slayer Inferno.
Its best modifier is Flawless.

====

.选段 2：对某游戏机制的讲解
====
Terraria's logic updates 60 times per second, meaning that if there is no immunity frame, any player in contact with a hostile entity will be hit 60 times in just a single second: even the weakest slime can instakill an unarmored player at this rate.

Hence, immunity frame was introduced to create a window for players to escape from the next hit, which is typically indicated by a distinct blinking visual effect. It sometimes serves as a bonus rather than a compensate. For instance, Brain of Confusion enables players to completely dodge an attack instead of being invulnerable only after taking the damage.

However the mechanism can be exploited to make fights way easier than they should be. Constantly taking low damage, players may buy immunity frames that negate high-damage attacks from elites or bosses. Not all hostiles would be tricked by this technique, though.

====

.选段 3：对某创意的解释
====
Speaking of sleeping, it has merely two features in the game: setting a spawn point or speeding up time. And how interesting would it be to spawn on an NPC? Forget about all those boring static spawn points, we can have a dynamic one that spices up our gameplay. I’m tired of looking at the same exact frame every time I die, and I’m sure you are too! This would also encourage players to build actual homes, not NPC prisons.

Moreover, it would let us to relieve stress. Calamity is a stressful mod enough, requiring constant attention especially while fighting bosses. So a break to refresh ourselves would be great. Now I ask you, what can you do in Calamity to take a break? Mining? Fishing? Grinding? No! Those or the risk of mobs still require some work. Instead, sleeping on the laps of a character who also needs love is truly awesome in order to mitigate pressure and change the pace.
====

