tag::attrs[]
:cc-by-name: CC BY 4.0
:link-cc-by: https://creativecommons.org/licenses/by/4.0/legalcode
:link-cc-by-deed: https://creativecommons.org/licenses/by/4.0/deed
:link-cc-image: https://mirrors.creativecommons.org/presskit/icons/cc.svg
:link-by-image: https://mirrors.creativecommons.org/presskit/icons/by.svg
:inline-cc: image:{link-cc-image}[CC, 16, 16]
:inline-by: image:{link-by-image}[BY, 16, 16]
end::attrs[]

tag::notes[]
tag::note-en[]
Except where noted, this work is licensed under {link-cc-by}[{cc-by-name} {inline-cc} {inline-by}].
end::note-en[]
end::notes[]

tag::deeds[]
tag::deed-en[]
[discrete]
=== *You are free to:*
Share:: copy and redistribute the material in any medium or format for any purpose, even commercially.
Adapt:: remix, transform, and build upon the material for any purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.

[discrete]
=== *Under the following terms:*
Attribution:: You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

No additional restrictions:: You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

[discrete]
=== *Notices:*
You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.

No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.
end::deed-en[]
end::deeds[]
